import Foundation
import Irgo  // Generated by gomobile bind

/// A native capability plugin. Plugins claim a namespace ("haptics") and
/// handle methods of the form "namespace.action" ("haptics.impact").
public protocol IrgoPlugin {
    /// Namespace prefix, e.g. "haptics" claims "haptics.*" methods.
    var namespace: String { get }

    /// Handle a call. `method` is the full method name ("haptics.impact").
    /// Called on the main queue. Return false if the method is not
    /// recognized; in that case the completion must not be called. When
    /// returning true, call the completion exactly once (any queue).
    func handle(method: String, params: [String: Any], completion: @escaping (Result<Any?, Error>) -> Void) -> Bool
}

/// Registry and dispatcher for native capability plugins.
///
/// Calls arrive from two directions and funnel through dispatch(...):
///   - JavaScript, via the "irgo" WKScriptMessageHandler ({type: "native"})
///   - Go, via mobile.SetNativeInvoker (native.Call in Go app code)
public final class IrgoNative {

    public static let shared = IrgoNative()

    /// Sentinel payload meaning "no plugin claims this method". Callers fall
    /// back to Go-registered handlers when they see it.
    public static let notSupported = "IRGO_NOT_SUPPORTED"

    private let lock = NSLock()
    private var plugins: [String: IrgoPlugin] = [:]
    private let goInvoker = IrgoGoInvoker()

    private init() {}

    /// Register a plugin. The last registration for a namespace wins.
    public func register(_ plugin: IrgoPlugin) {
        lock.lock()
        plugins[plugin.namespace] = plugin
        lock.unlock()
    }

    /// Connect the registry to the Go runtime so Go code can invoke native
    /// capabilities. Called once during shell initialization.
    public func attachToGo() {
        MobileSetNativeInvoker(goInvoker)
    }

    /// Dispatch a native call to the plugin registry.
    ///
    /// The completion receives (ok, payloadJSON):
    ///   - ok == true: payloadJSON is the JSON-encoded result ("null" when
    ///     the plugin produced no value)
    ///   - ok == false: payloadJSON is IrgoNative.notSupported when no plugin
    ///     claims the method, otherwise a JSON-encoded error message string
    /// It is always invoked exactly once, on the main queue.
    func dispatch(method: String, paramsJSON: String, completion: @escaping (Bool, String) -> Void) {
        let namespace = method.components(separatedBy: ".").first ?? ""

        lock.lock()
        let plugin = plugins[namespace]
        lock.unlock()

        guard let plugin = plugin, method.contains(".") else {
            DispatchQueue.main.async {
                completion(false, IrgoNative.notSupported)
            }
            return
        }

        let params = IrgoNative.decodeParams(paramsJSON)

        // Plugins touch UIKit; run them on the main queue.
        DispatchQueue.main.async {
            let finished = IrgoOnceFlag()
            let claimed = plugin.handle(method: method, params: params) { result in
                guard finished.trySet() else { return }
                let deliver = {
                    switch result {
                    case .success(let payload):
                        completion(true, IrgoNative.encodePayload(payload))
                    case .failure(let error):
                        completion(false, IrgoJS.stringLiteral(error.localizedDescription))
                    }
                }
                if Thread.isMainThread {
                    deliver()
                } else {
                    DispatchQueue.main.async(execute: deliver)
                }
            }
            if !claimed && finished.trySet() {
                completion(false, IrgoNative.notSupported)
            }
        }
    }

    // MARK: - JSON helpers

    private static func decodeParams(_ paramsJSON: String) -> [String: Any] {
        guard let data = paramsJSON.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        return object
    }

    /// JSON-encode a plugin result. nil encodes as "null".
    private static func encodePayload(_ payload: Any?) -> String {
        guard let payload = payload else { return "null" }
        if let data = try? JSONSerialization.data(withJSONObject: payload, options: [.fragmentsAllowed]),
           let json = String(data: data, encoding: .utf8) {
            return json
        }
        return "null"
    }
}

/// Adapter registered with mobile.SetNativeInvoker: receives calls from Go
/// code, dispatches them to the plugin registry, and reports results back
/// through MobileNativeResult.
private final class IrgoGoInvoker: NSObject, MobileNativeInvokerProtocol {
    func invoke(_ callID: String?, method: String?, paramsJSON: String?) {
        guard let callID = callID, !callID.isEmpty else { return }
        IrgoNative.shared.dispatch(method: method ?? "", paramsJSON: paramsJSON ?? "{}") { ok, payloadJSON in
            MobileNativeResult(callID, ok, payloadJSON)
        }
    }
}

/// One-shot guard ensuring a completion fires exactly once.
private final class IrgoOnceFlag {
    private let lock = NSLock()
    private var fired = false

    func trySet() -> Bool {
        lock.lock()
        defer { lock.unlock() }
        if fired {
            return false
        }
        fired = true
        return true
    }
}
