import Foundation
import WebKit
import Irgo  // Generated by gomobile bind

/// Main bridge class that connects iOS to the Go framework
public class IrgoBridge: NSObject {
    public static let shared = IrgoBridge()

    private var webView: WKWebView?
    private var schemeHandler: IrgoSchemeHandler?

    private override init() {
        super.init()
        // Initialize the Go bridge
        MobileInitialize()
    }

    /// Configure the bridge with a WebView
    public func configure(webView: WKWebView) {
        self.webView = webView
    }

    /// Check if the bridge is ready
    public var isReady: Bool {
        return MobileIsReady()
    }

    /// Handle an HTTP request and return the response
    public func handleRequest(
        method: String,
        url: String,
        headers: [String: String] = [:],
        body: Data? = nil
    ) -> IrgoResponse {
        let headersJSON = try? JSONSerialization.data(withJSONObject: headers)
        let headersString = headersJSON.flatMap { String(data: $0, encoding: .utf8) } ?? "{}"

        guard let response = MobileHandleRequest(method, url, headersString, body) else {
            return IrgoResponse(status: 500, headers: [:], body: Data())
        }

        return IrgoResponse(from: response)
    }

    /// Get the initial HTML page content
    public func renderInitialPage() -> String {
        return MobileRenderInitialPage()
    }

    /// Shutdown the bridge
    public func shutdown() {
        MobileShutdown()
    }
}

/// Swift-friendly response wrapper
public struct IrgoResponse {
    public let status: Int
    public let headers: [String: String]
    public let body: Data

    public var bodyString: String {
        return String(data: body, encoding: .utf8) ?? ""
    }

    init(status: Int, headers: [String: String], body: Data) {
        self.status = status
        self.headers = headers
        self.body = body
    }

    init(from response: MobileResponse) {
        self.status = Int(response.status)
        self.body = response.body ?? Data()
        self.headers = IrgoResponse.parseHeaders(response.headers)
    }

    /// Parse the bridge's headers wire format. Values may be a string or an
    /// array of strings (multi-value headers such as Set-Cookie); arrays are
    /// joined with ", " for this flat [String: String] view. A plain
    /// [String: String] cast would fail wholesale — dropping ALL headers,
    /// including Content-Type — as soon as any value is an array.
    static func parseHeaders(_ headersJSON: String) -> [String: String] {
        guard let data = headersJSON.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        var headers: [String: String] = [:]
        for (key, value) in object {
            if let single = value as? String {
                headers[key] = single
            } else if let many = value as? [Any] {
                let strings = many.compactMap { $0 as? String }
                if !strings.isEmpty {
                    headers[key] = strings.joined(separator: ", ")
                }
            }
        }
        return headers
    }
}

/// Helpers for building JavaScript source passed to evaluateJavaScript.
public enum IrgoJS {
    /// Encode a Swift string as a double-quoted JavaScript string literal.
    /// The output is also a valid JSON string literal, so it can be used both
    /// for JS call arguments and for JSON payload strings.
    public static func stringLiteral(_ value: String) -> String {
        var out = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\"":
                out += "\\\""
            case "\\":
                out += "\\\\"
            case "\n":
                out += "\\n"
            case "\r":
                out += "\\r"
            case "\t":
                out += "\\t"
            case "\u{2028}":
                out += "\\u2028"
            case "\u{2029}":
                out += "\\u2029"
            default:
                if scalar.value < 0x20 {
                    out += String(format: "\\u%04x", scalar.value)
                } else {
                    out.append(Character(scalar))
                }
            }
        }
        out += "\""
        return out
    }
}
