package com.irgo

import android.webkit.WebView
import irgo.mobile.Mobile
import org.json.JSONObject

/**
 * Main bridge class that connects Android to the Go framework.
 *
 * The underlying gomobile-bound class is `irgo.mobile.Mobile` — it's
 * generated by `gomobile bind -javapkg irgo` from the user app's
 * `mobile/` Go package. We wrap it here so the rest of the Android code
 * can talk to a Kotlin-friendly API.
 */
object IrgoBridge {

    private var webView: WebView? = null

    /**
     * Initialize the Go bridge. Call once at app startup.
     */
    fun initialize() {
        Mobile.initialize()
    }

    /**
     * Configure the bridge with a WebView
     */
    fun configure(webView: WebView) {
        this.webView = webView
    }

    /**
     * Check if the bridge is ready
     */
    val isReady: Boolean
        get() = Mobile.isReady()

    /**
     * Handle an HTTP request and return the response
     */
    fun handleRequest(
        method: String,
        url: String,
        headers: Map<String, String> = emptyMap(),
        body: ByteArray? = null
    ): IrgoResponse {
        val headersJson = JSONObject(headers).toString()
        val response = Mobile.handleRequest(method, url, headersJson, body)
            ?: return IrgoResponse(500, emptyMap(), ByteArray(0))

        return IrgoResponse.from(response)
    }

    /**
     * Get the initial HTML page content
     */
    fun renderInitialPage(): String {
        return Mobile.renderInitialPage()
    }

    /**
     * Shutdown the bridge
     */
    fun shutdown() {
        Mobile.shutdown()
    }
}

/**
 * Kotlin-friendly response wrapper.
 *
 * `irgo.mobile.Response` is the gomobile-bound Go struct from
 * `mobile/mobile.go` — we copy the fields out so callers don't have to
 * deal with the generated proxy object.
 */
data class IrgoResponse(
    val status: Int,
    val headers: Map<String, String>,
    val body: ByteArray
) {
    val bodyString: String
        get() = String(body, Charsets.UTF_8)

    companion object {
        fun from(response: irgo.mobile.Response): IrgoResponse {
            val headers = mutableMapOf<String, String>()
            try {
                val headersJson = JSONObject(response.headers)
                headersJson.keys().forEach { key ->
                    headers[key] = headersJson.getString(key)
                }
            } catch (e: Exception) {
                // Ignore JSON parsing errors
            }

            return IrgoResponse(
                status = response.status.toInt(),
                headers = headers,
                body = response.body ?: ByteArray(0)
            )
        }
    }

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false
        other as IrgoResponse
        return status == other.status && headers == other.headers && body.contentEquals(other.body)
    }

    override fun hashCode(): Int {
        var result = status
        result = 31 * result + headers.hashCode()
        result = 31 * result + body.contentHashCode()
        return result
    }
}
