import Foundation
import WebKit
import Irgo  // Generated by gomobile bind

/// Main bridge class that connects iOS to the Go framework
public class IrgoBridge: NSObject {
    public static let shared = IrgoBridge()

    private var webView: WKWebView?
    private var schemeHandler: IrgoSchemeHandler?

    private override init() {
        super.init()
        // Initialize the Go bridge
        MobileInitialize()
    }

    /// Configure the bridge with a WebView
    public func configure(webView: WKWebView) {
        self.webView = webView
    }

    /// Check if the bridge is ready
    public var isReady: Bool {
        return MobileIsReady()
    }

    /// Handle an HTTP request and return the response
    public func handleRequest(
        method: String,
        url: String,
        headers: [String: String] = [:],
        body: Data? = nil
    ) -> IrgoResponse {
        let headersJSON = try? JSONSerialization.data(withJSONObject: headers)
        let headersString = headersJSON.flatMap { String(data: $0, encoding: .utf8) } ?? "{}"

        guard let response = MobileHandleRequest(method, url, headersString, body) else {
            return IrgoResponse(status: 500, headers: [:], body: Data())
        }

        return IrgoResponse(from: response)
    }

    /// Get the initial HTML page content
    public func renderInitialPage() -> String {
        return MobileRenderInitialPage()
    }

    /// Shutdown the bridge
    public func shutdown() {
        MobileShutdown()
    }
}

/// Swift-friendly response wrapper
public struct IrgoResponse {
    public let status: Int
    public let headers: [String: String]
    public let body: Data

    public var bodyString: String {
        return String(data: body, encoding: .utf8) ?? ""
    }

    init(status: Int, headers: [String: String], body: Data) {
        self.status = status
        self.headers = headers
        self.body = body
    }

    init(from response: CoreResponse) {
        self.status = Int(response.status)
        self.body = response.body ?? Data()

        // Parse headers from JSON
        if let headersData = response.headers.data(using: .utf8),
           let parsed = try? JSONSerialization.jsonObject(with: headersData) as? [String: String] {
            self.headers = parsed
        } else {
            self.headers = [:]
        }
    }
}

/// Helpers for building JavaScript source passed to evaluateJavaScript.
public enum IrgoJS {
    /// Encode a Swift string as a double-quoted JavaScript string literal.
    /// The output is also a valid JSON string literal, so it can be used both
    /// for JS call arguments and for JSON payload strings.
    public static func stringLiteral(_ value: String) -> String {
        var out = "\""
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\"":
                out += "\\\""
            case "\\":
                out += "\\\\"
            case "\n":
                out += "\\n"
            case "\r":
                out += "\\r"
            case "\t":
                out += "\\t"
            case "\u{2028}":
                out += "\\u2028"
            case "\u{2029}":
                out += "\\u2029"
            default:
                if scalar.value < 0x20 {
                    out += String(format: "\\u%04x", scalar.value)
                } else {
                    out.append(Character(scalar))
                }
            }
        }
        out += "\""
        return out
    }
}
