import UIKit
import WebKit
import Irgo  // Generated by gomobile bind

/// Main WebView controller for Irgo apps
open class IrgoWebViewController: UIViewController {

    /// The WebView instance
    public private(set) var webView: WKWebView!

    /// The scheme handler for intercepting requests
    private let schemeHandler = IrgoSchemeHandler()

    /// The postMessage handler used by /_irgo/bridge.js for native calls and
    /// virtual WebSockets. A dedicated object with weak references avoids the
    /// retain cycle WKUserContentController would otherwise create.
    private let messageHandler = IrgoScriptMessageHandler()

    /// One-time process-wide runtime setup guard
    private static var runtimeInitialized = false

    /// Bootstrap script injected at document start. The full JS bridge is
    /// loaded by app layouts via <script src="/_irgo/bridge.js">; this only
    /// tags the platform and reroutes relative fetch() URLs into the irgo://
    /// scheme so Datastar requests hit the streaming scheme handler.
    private var bootstrapScript: String {
        return """
        (function() {
            window.__IRGO_PLATFORM__ = 'ios';
            // Tells /_irgo/bridge.js this shell implements the {type:"native"}
            // message, so irgo.native() uses it instead of the HTTP fallback.
            window.__IRGO_IOS_NATIVE__ = true;

            const originalFetch = window.fetch;

            function toIrgoUrl(url) {
                if (typeof url !== 'string') return url;
                if (url.startsWith('/')) return 'irgo://app' + url;
                if (!url.includes('://')) return 'irgo://app/' + url;
                return url;
            }

            window.fetch = function(input, init) {
                if (typeof input === 'string') {
                    return originalFetch.call(window, toIrgoUrl(input), init);
                }
                if (input && typeof input.url === 'string') {
                    const rewritten = toIrgoUrl(input.url);
                    if (rewritten !== input.url) {
                        return originalFetch.call(window, new Request(rewritten, input), init);
                    }
                }
                return originalFetch.call(window, input, init);
            };

            console.log('Irgo bootstrap initialized');
        })();
        """
    }

    open override func viewDidLoad() {
        super.viewDidLoad()
        IrgoWebViewController.initializeRuntimeIfNeeded()
        setupWebView()
        observeAppLifecycle()
        loadInitialPage()
    }

    deinit {
        NotificationCenter.default.removeObserver(self)
        webView?.configuration.userContentController.removeScriptMessageHandler(forName: "irgo")
    }

    // MARK: - Runtime setup

    /// One-time process setup: cookie persistence and the native plugin
    /// registry. Runs before the first WebView is created.
    private static func initializeRuntimeIfNeeded() {
        guard !runtimeInitialized else { return }
        runtimeInitialized = true

        // Persist Go bridge state (cookie jar) in Application Support so
        // login sessions survive app restarts.
        let fileManager = FileManager.default
        if let supportDir = fileManager.urls(for: .applicationSupportDirectory, in: .userDomainMask).first {
            let stateDir = supportDir.appendingPathComponent("Irgo", isDirectory: true)
            try? fileManager.createDirectory(at: stateDir, withIntermediateDirectories: true)
            MobileSetStateDir(stateDir.path)
        }

        // Native capability plugins (device, haptics, clipboard, share,
        // browser, storage, notifications), reachable from JS and from Go.
        IrgoNative.shared.registerBuiltins()
        IrgoNative.shared.attachToGo()
    }

    // MARK: - WebView setup

    /// Set up the WebView with custom configuration
    private func setupWebView() {
        // Create configuration
        let config = WKWebViewConfiguration()

        // Register custom scheme handler (streams responses from Go)
        config.setURLSchemeHandler(schemeHandler, forURLScheme: IrgoSchemeHandler.scheme)

        // Register the postMessage channel used by the JS bridge
        config.userContentController.add(messageHandler, name: "irgo")

        // Add bootstrap script
        let userScript = WKUserScript(
            source: bootstrapScript,
            injectionTime: .atDocumentStart,
            forMainFrameOnly: false
        )
        config.userContentController.addUserScript(userScript)

        // Configure preferences
        let preferences = WKWebpagePreferences()
        preferences.allowsContentJavaScript = true
        config.defaultWebpagePreferences = preferences

        // Allow inline media playback
        config.allowsInlineMediaPlayback = true
        config.mediaTypesRequiringUserActionForPlayback = []

        // Create WebView
        webView = WKWebView(frame: view.bounds, configuration: config)
        webView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        webView.navigationDelegate = self
        webView.scrollView.contentInsetAdjustmentBehavior = .never

        // Configure for mobile
        webView.scrollView.bounces = true
        webView.allowsBackForwardNavigationGestures = true

        // Add to view
        view.addSubview(webView)

        // Wire the bridges to this WebView
        messageHandler.webView = webView
        IrgoBridge.shared.configure(webView: webView)
        IrgoWebSocketBridge.shared.configure(webView: webView)
    }

    // MARK: - App lifecycle

    /// Forward app lifecycle transitions to the Go bridge (cookie jar
    /// persistence, app-registered lifecycle handlers).
    private func observeAppLifecycle() {
        let center = NotificationCenter.default
        center.addObserver(
            self,
            selector: #selector(handleDidEnterBackground),
            name: UIApplication.didEnterBackgroundNotification,
            object: nil
        )
        center.addObserver(
            self,
            selector: #selector(handleWillEnterForeground),
            name: UIApplication.willEnterForegroundNotification,
            object: nil
        )
    }

    @objc private func handleDidEnterBackground() {
        MobileOnBackground()
    }

    @objc private func handleWillEnterForeground() {
        MobileOnForeground()
    }

    // MARK: - Navigation

    /// Load the initial HTML page. Rendering runs off the main thread: the
    /// Go "/" handler may call native.Call, whose plugins execute on the
    /// main queue — rendering synchronously here would deadlock until the
    /// 30s native-call timeout.
    private func loadInitialPage() {
        DispatchQueue.global(qos: .userInitiated).async { [weak self] in
            let html = IrgoBridge.shared.renderInitialPage()
            DispatchQueue.main.async {
                // Load with base URL using our custom scheme
                self?.webView.loadHTMLString(html, baseURL: URL(string: "irgo://app/"))
            }
        }
    }

    /// Navigate to a path within the app
    public func navigate(to path: String) {
        var url = path
        if !url.hasPrefix("irgo://") {
            if url.hasPrefix("/") {
                url = "irgo://app" + url
            } else {
                url = "irgo://app/" + url
            }
        }

        if let navURL = URL(string: url) {
            webView.load(URLRequest(url: navURL))
        }
    }

    /// Inject JavaScript into the WebView
    public func evaluateJavaScript(_ script: String, completion: ((Any?, Error?) -> Void)? = nil) {
        webView.evaluateJavaScript(script, completionHandler: completion)
    }
}

// MARK: - WKNavigationDelegate
extension IrgoWebViewController: WKNavigationDelegate {

    public func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
        // Page loaded successfully
    }

    public func webView(_ webView: WKWebView, didFail navigation: WKNavigation!, withError error: Error) {
        print("Irgo navigation failed: \(error.localizedDescription)")
    }

    public func webView(
        _ webView: WKWebView,
        decidePolicyFor navigationAction: WKNavigationAction,
        decisionHandler: @escaping (WKNavigationActionPolicy) -> Void
    ) {
        guard let url = navigationAction.request.url else {
            decisionHandler(.cancel)
            return
        }

        // Allow irgo:// scheme
        if url.scheme == IrgoSchemeHandler.scheme {
            decisionHandler(.allow)
            return
        }

        // Allow data: URLs (for initial HTML load)
        if url.scheme == "data" || url.scheme == "about" {
            decisionHandler(.allow)
            return
        }

        // For external URLs, open in Safari
        if url.scheme == "http" || url.scheme == "https" {
            UIApplication.shared.open(url)
            decisionHandler(.cancel)
            return
        }

        decisionHandler(.allow)
    }
}

// MARK: - Script message handler

/// Receives window.webkit.messageHandlers.irgo.postMessage(...) bodies from
/// the JS bridge and routes them to the native plugin registry or the
/// WebSocket bridge. Holds only weak references, so it cannot create a
/// retain cycle through WKUserContentController.
final class IrgoScriptMessageHandler: NSObject, WKScriptMessageHandler {

    weak var webView: WKWebView?

    /// Serial queue for Go bridge calls. WKScriptMessageHandler delivers on
    /// the main thread, but Go WebSocket handlers (OnConnect/OnMessage) run
    /// synchronously inside these calls and may invoke native.Call — whose
    /// plugins execute on the main queue. Dispatching off-main keeps the
    /// main queue free and makes that re-entrancy deadlock impossible.
    private let bridgeQueue = DispatchQueue(label: "irgo.bridge.messages")

    func userContentController(_ userContentController: WKUserContentController, didReceive message: WKScriptMessage) {
        guard message.name == "irgo",
              let body = message.body as? [String: Any],
              let type = body["type"] as? String else {
            return
        }

        switch type {
        case "native":
            handleNative(body)
        case "ws_connect":
            bridgeQueue.async { self.handleWebSocketConnect(body) }
        case "ws_send":
            if let sessionID = body["sessionId"] as? String,
               let data = body["data"] as? String {
                bridgeQueue.async {
                    _ = try? IrgoWebSocketBridge.shared.send(sessionID: sessionID, data: data)
                }
            }
        case "ws_close":
            if let sessionID = body["sessionId"] as? String {
                bridgeQueue.async {
                    IrgoWebSocketBridge.shared.close(sessionID: sessionID)
                }
            }
        default:
            break
        }
    }

    /// {type: "native", requestId, method, params} where params is a JSON
    /// string. Results go back via window._irgo_native_result(requestId, ok,
    /// payloadJSON); "IRGO_NOT_SUPPORTED" triggers the Go-handler fallback.
    private func handleNative(_ body: [String: Any]) {
        guard let requestID = body["requestId"] as? String,
              let method = body["method"] as? String else {
            return
        }
        let paramsJSON = body["params"] as? String ?? "{}"

        IrgoNative.shared.dispatch(method: method, paramsJSON: paramsJSON) { [weak self] ok, payloadJSON in
            self?.callJS(
                "window._irgo_native_result(\(IrgoJS.stringLiteral(requestID)), \(ok), \(IrgoJS.stringLiteral(payloadJSON)))"
            )
        }
    }

    /// {type: "ws_connect", requestId, url}
    private func handleWebSocketConnect(_ body: [String: Any]) {
        guard let requestID = body["requestId"] as? String,
              let url = body["url"] as? String else {
            return
        }
        do {
            let sessionID = try IrgoWebSocketBridge.shared.connect(url: url)
            callJS("window._irgo_ws_connected(\(IrgoJS.stringLiteral(requestID)), \(IrgoJS.stringLiteral(sessionID)))")
        } catch {
            callJS("window._irgo_ws_connect_error(\(IrgoJS.stringLiteral(requestID)), \(IrgoJS.stringLiteral(error.localizedDescription)))")
        }
    }

    /// Evaluate JavaScript on the main thread.
    private func callJS(_ script: String) {
        DispatchQueue.main.async { [weak self] in
            self?.webView?.evaluateJavaScript(script, completionHandler: nil)
        }
    }
}
