import Foundation
import WebKit
import Irgo  // Generated by gomobile bind

/// Custom URL scheme handler that intercepts irgo:// requests and streams
/// them through the Go bridge. Responses arrive progressively: each flush on
/// the Go side becomes one chunk delivered to the WebView, so Datastar SSE
/// events are processed while the handler is still running.
public class IrgoSchemeHandler: NSObject, WKURLSchemeHandler {

    /// The URL scheme to intercept (e.g., "irgo")
    public static let scheme = "irgo"

    /// Registry of in-flight scheme tasks. WKWebView forbids calling any
    /// method on a WKURLSchemeTask after webView(_:stop:) has been invoked
    /// for it, so every stream callback re-checks membership on the main
    /// thread before touching the task.
    private let lock = NSLock()
    private var liveTasks: [ObjectIdentifier: IrgoTaskEntry] = [:]

    // MARK: - WKURLSchemeHandler

    /// Start handling a request (called on the main thread).
    public func webView(_ webView: WKWebView, start urlSchemeTask: WKURLSchemeTask) {
        guard let url = urlSchemeTask.request.url else {
            urlSchemeTask.didFailWithError(IrgoError.invalidURL)
            return
        }

        // Convert irgo:// URL to an app path:
        // irgo://app/path?query -> /path?query
        var path = url.path
        if path.isEmpty {
            path = "/"
        }
        if let query = url.query, !query.isEmpty {
            path += "?" + query
        }

        // Get HTTP method
        let method = urlSchemeTask.request.httpMethod ?? "GET"

        // Forward request headers (Accept, Content-Type, Datastar headers...)
        var headers: [String: String] = [:]
        urlSchemeTask.request.allHTTPHeaderFields?.forEach { key, value in
            headers[key] = value
        }
        let headersJSON = (try? JSONSerialization.data(withJSONObject: headers))
            .flatMap { String(data: $0, encoding: .utf8) } ?? "{}"

        // Get body (WKWebView sometimes delivers it as a stream)
        let body = IrgoSchemeHandler.requestBody(of: urlSchemeTask.request)

        // Mark the task live before starting the stream so callbacks that
        // fire immediately can find it.
        let taskID = ObjectIdentifier(urlSchemeTask)
        register(taskID)

        let callback = IrgoStreamTaskCallback(handler: self, task: urlSchemeTask, url: url)
        let handle = MobileHandleRequestStream(method, path, headersJSON, body, callback)
        attach(handle, to: taskID)
    }

    /// Stop handling a request (called on the main thread when the WebView
    /// cancels it). After this returns, the task must never be touched again.
    public func webView(_ webView: WKWebView, stop urlSchemeTask: WKURLSchemeTask) {
        let entry = unregister(ObjectIdentifier(urlSchemeTask))
        entry?.handle?.cancel()
    }

    // MARK: - Live task registry

    private func register(_ taskID: ObjectIdentifier) {
        lock.lock()
        liveTasks[taskID] = IrgoTaskEntry()
        lock.unlock()
    }

    /// Store the Go stream handle so stop can cancel the request. If the
    /// stream already completed, cancel the handle (a no-op after
    /// completion) instead of leaking a registry entry.
    private func attach(_ handle: MobileStreamHandle?, to taskID: ObjectIdentifier) {
        lock.lock()
        let entry = liveTasks[taskID]
        entry?.handle = handle
        lock.unlock()
        if entry == nil {
            handle?.cancel()
        }
    }

    /// Whether the task is still live (i.e., stop has not been called and the
    /// stream has not finished).
    fileprivate func isLive(_ taskID: ObjectIdentifier) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return liveTasks[taskID] != nil
    }

    /// Remove the task from the registry, returning its entry if it was
    /// still live. Callers deliver at most one terminal event (didFinish or
    /// didFailWithError) when this returns non-nil.
    @discardableResult
    fileprivate func unregister(_ taskID: ObjectIdentifier) -> IrgoTaskEntry? {
        lock.lock()
        defer { lock.unlock() }
        return liveTasks.removeValue(forKey: taskID)
    }

    // MARK: - Helpers

    /// Read the request body, draining httpBodyStream when httpBody is nil.
    private static func requestBody(of request: URLRequest) -> Data? {
        if let body = request.httpBody {
            return body
        }
        guard let stream = request.httpBodyStream else {
            return nil
        }
        stream.open()
        defer { stream.close() }
        var data = Data()
        let bufferSize = 16 * 1024
        var buffer = [UInt8](repeating: 0, count: bufferSize)
        while stream.hasBytesAvailable {
            let read = stream.read(&buffer, maxLength: bufferSize)
            if read <= 0 {
                break
            }
            data.append(buffer, count: read)
        }
        return data
    }
}

/// Registry entry for one in-flight scheme task.
private final class IrgoTaskEntry {
    /// Go-side stream handle, cancelled when the WebView stops the task.
    var handle: MobileStreamHandle?
}

/// Bridges one Go response stream onto one WKURLSchemeTask.
///
/// Go delivers callbacks sequentially from a background thread: onResponse
/// once, onChunk zero or more times, onComplete once (always last). Each
/// callback hops to the main thread and re-checks that the task is still
/// live before touching it, honoring the WKURLSchemeHandler contract.
private final class IrgoStreamTaskCallback: NSObject, MobileStreamCallbackProtocol {

    private weak var handler: IrgoSchemeHandler?
    private let task: WKURLSchemeTask
    private let taskID: ObjectIdentifier
    private let url: URL

    /// Whether didReceive(response) has been delivered. Main-thread only.
    private var deliveredResponse = false

    init(handler: IrgoSchemeHandler, task: WKURLSchemeTask, url: URL) {
        self.handler = handler
        self.task = task
        self.taskID = ObjectIdentifier(task)
        self.url = url
    }

    func onResponse(_ status: Int, headersJSON: String?) {
        let headerFields = IrgoStreamTaskCallback.parseHeaders(headersJSON)
        DispatchQueue.main.async {
            guard let handler = self.handler, handler.isLive(self.taskID) else { return }
            guard let response = HTTPURLResponse(
                url: self.url,
                statusCode: status,
                httpVersion: "HTTP/1.1",
                headerFields: headerFields
            ) else {
                // Terminal failure: unregister first so later callbacks
                // become no-ops, and cancel the Go stream.
                let entry = handler.unregister(self.taskID)
                entry?.handle?.cancel()
                self.task.didFailWithError(IrgoError.responseError)
                return
            }
            self.deliveredResponse = true
            self.task.didReceive(response)
        }
    }

    func onChunk(_ chunk: Data?) {
        guard let chunk = chunk, !chunk.isEmpty else { return }
        DispatchQueue.main.async {
            guard let handler = self.handler, handler.isLive(self.taskID) else { return }
            // WebKit requires a response before any data.
            guard self.deliveredResponse else { return }
            self.task.didReceive(chunk)
        }
    }

    func onComplete(_ errorMessage: String?) {
        DispatchQueue.main.async {
            guard let handler = self.handler, handler.unregister(self.taskID) != nil else { return }
            if let message = errorMessage, !message.isEmpty {
                self.task.didFailWithError(IrgoError.stream(message))
            } else if self.deliveredResponse {
                self.task.didFinish()
            } else {
                // didFinish without a prior response violates the contract.
                self.task.didFailWithError(IrgoError.responseError)
            }
        }
    }

    /// Parse the bridge's response headers JSON. Values may be a string or an
    /// array of strings (multi-value headers such as Set-Cookie); arrays are
    /// joined with ", " since HTTPURLResponse takes a flat [String: String].
    private static func parseHeaders(_ headersJSON: String?) -> [String: String] {
        guard let headersJSON = headersJSON,
              let data = headersJSON.data(using: .utf8),
              let object = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return [:]
        }
        var headers: [String: String] = [:]
        for (key, value) in object {
            if let single = value as? String {
                headers[key] = single
            } else if let many = value as? [Any] {
                let strings = many.compactMap { $0 as? String }
                if !strings.isEmpty {
                    headers[key] = strings.joined(separator: ", ")
                }
            } else if let number = value as? NSNumber {
                headers[key] = number.stringValue
            }
        }
        return headers
    }
}

/// Irgo specific errors
public enum IrgoError: Error, LocalizedError {
    case invalidURL
    case responseError
    case bridgeNotInitialized
    case unsupported(String)
    case stream(String)

    public var errorDescription: String? {
        switch self {
        case .invalidURL:
            return "Invalid URL"
        case .responseError:
            return "Failed to build HTTP response"
        case .bridgeNotInitialized:
            return "Irgo bridge not initialized"
        case .unsupported(let message):
            return message
        case .stream(let message):
            return message
        }
    }
}
