import Foundation
import WebKit
import Irgo  // Generated by gomobile bind

/// Bridge for virtual WebSocket connections between the WebView and the Go
/// WebSocket hub. The JS bridge (window.WebSocket replacement) drives
/// connect/send/close via the "irgo" script message handler; Go pushes
/// messages back through the MobileWebSocketCallbackProtocol callbacks.
public class IrgoWebSocketBridge: NSObject {
    public static let shared = IrgoWebSocketBridge()

    private weak var webView: WKWebView?
    private let lock = NSLock()
    private var activeSessions: Set<String> = []

    private override init() {
        super.init()
        // Register as WebSocket callback handler
        MobileSetWebSocketCallback(self)
    }

    /// Configure with a WebView for message delivery
    public func configure(webView: WKWebView) {
        self.webView = webView
    }

    /// Connect to a virtual WebSocket
    /// - Parameter url: The WebSocket URL (e.g., "irgo://ws/chat")
    /// - Returns: Session ID
    public func connect(url: String) throws -> String {
        var error: NSError?
        // MobileWebSocketConnect returns a non-optional String (gomobile
        // generates `NSString* _Nonnull` + explicit error pointer), so there
        // is nothing to conditionally bind — just reject empty sessions.
        let sessionID = MobileWebSocketConnect(url, &error)

        if let error = error {
            throw error
        }

        guard !sessionID.isEmpty else {
            throw IrgoError.bridgeNotInitialized
        }

        lock.lock()
        activeSessions.insert(sessionID)
        lock.unlock()
        return sessionID
    }

    /// Send a message through a virtual WebSocket
    /// - Parameters:
    ///   - sessionID: The session ID from connect()
    ///   - data: JSON-encoded message data
    @discardableResult
    public func send(sessionID: String, data: String) throws -> String? {
        var error: NSError?
        let response = MobileWebSocketSend(sessionID, data, &error)

        if let error = error {
            throw error
        }

        return response
    }

    /// Close a virtual WebSocket connection
    public func close(sessionID: String) {
        var error: NSError?
        // MobileWebSocketClose takes an explicit error pointer (gomobile
        // generates `BOOL ... (sessionID, NSError** error)`).
        MobileWebSocketClose(sessionID, &error)
        if let error = error {
            print("Irgo: error closing WebSocket: \(error)")
        }
        lock.lock()
        activeSessions.remove(sessionID)
        lock.unlock()
    }

    /// Close all active sessions
    public func closeAll() {
        lock.lock()
        let sessions = activeSessions
        lock.unlock()
        for sessionID in sessions {
            close(sessionID: sessionID)
        }
    }

    /// Evaluate JavaScript on the main thread.
    private func callJS(_ script: String) {
        DispatchQueue.main.async { [weak self] in
            self?.webView?.evaluateJavaScript(script, completionHandler: nil)
        }
    }
}

// MARK: - MobileWebSocketCallbackProtocol
extension IrgoWebSocketBridge: MobileWebSocketCallbackProtocol {

    /// Called by Go when a message should be delivered to the WebView.
    public func onMessage(_ sessionID: String?, data: String?) {
        guard let sessionID = sessionID, let data = data else { return }
        callJS("window._irgo_ws_message(\(IrgoJS.stringLiteral(sessionID)), \(IrgoJS.stringLiteral(data)))")
    }

    /// Called by Go when a WebSocket session is closed.
    public func onClose(_ sessionID: String?, code: Int, reason: String?) {
        guard let sessionID = sessionID else { return }

        lock.lock()
        activeSessions.remove(sessionID)
        lock.unlock()

        callJS("window._irgo_ws_close(\(IrgoJS.stringLiteral(sessionID)), \(code), \(IrgoJS.stringLiteral(reason ?? "")))")
    }

    /// Called by Go when an error occurs on a session.
    public func onError(_ sessionID: String?, errorMsg: String?) {
        guard let sessionID = sessionID else { return }
        callJS("window._irgo_ws_error(\(IrgoJS.stringLiteral(sessionID)), \(IrgoJS.stringLiteral(errorMsg ?? "")))")
    }
}
