// Cleaning generated output. Everything irgo produces is reproducible from
// source, so removing it is always safe — but knowing *which* paths are
// generated is not obvious, and a stale artifact is a genuinely confusing
// failure (a framework built by an older irgo exposes an older bridge API, and
// the native shells then fail to compile against it).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// cleanTarget is one removable path and why it is safe to remove.
type cleanTarget struct {
	path string
	why  string
	// deep marks output that is expensive to rebuild — dependency trees and
	// downloaded toolchains. Removed only with --all, so the common case stays
	// fast.
	deep bool
}

func cleanTargets() []cleanTarget {
	return []cleanTarget{
		{"build", "compiled output (frameworks, AARs, desktop apps, web binary)", false},
		{"dist", "store packages from irgo app package", false},
		{"tmp", "scratch output", false},
		{"ios/Example", "native iOS shell — scaffolded from the CLI's templates", false},
		{"android/Example", "native Android shell — scaffolded from the CLI's templates", false},
		{"static/css/output.css", "generated by irgo project assets", false},
		{"go.work", "written by mobile builds for the gomobile workspace", false},
		{"go.work.sum", "written by mobile builds for the gomobile workspace", false},
		{"node_modules", "frontend dependencies — refetched by irgo project assets", true},
		{".gradle", "Gradle caches", true},
	}
}

// runClean removes generated output. It never touches anything a person wrote:
// every path here is either produced by an irgo command or scaffolded from the
// CLI's own templates.
func runClean(all bool) error {
	if _, err := os.Stat("go.mod"); err != nil {
		return fmt.Errorf("no go.mod here — run irgo project clean from your project root")
	}

	var removed, skipped int
	for _, t := range cleanTargets() {
		if t.deep && !all {
			if _, err := os.Stat(t.path); err == nil {
				skipped++
			}
			continue
		}
		if _, err := os.Stat(t.path); err != nil {
			continue
		}
		if err := os.RemoveAll(t.path); err != nil {
			return fmt.Errorf("removing %s: %w", t.path, err)
		}
		fmt.Printf("  removed %-24s %s\n", t.path, t.why)
		removed++
	}

	// Removing ios/Example leaves an empty ios/ behind, which looks like a
	// half-deleted project rather than a clean one. os.Remove only succeeds on
	// an empty directory, so a project that keeps its own files there is safe.
	for _, d := range []string{"ios", "android"} {
		if err := os.Remove(d); err == nil {
			fmt.Printf("  removed %-24s empty after removing the generated shell\n", d)
			removed++
		}
	}

	// Generated Go from templ, which lives beside its .templ source rather
	// than in a build directory.
	n, err := removeTemplGenerated()
	if err != nil {
		return err
	}
	removed += n

	if removed == 0 {
		fmt.Println("Nothing to clean.")
	} else {
		fmt.Printf("\n%d path(s) removed. Rebuild with: irgo app build <target>\n", removed)
	}
	if skipped > 0 {
		fmt.Printf("%d expensive path(s) kept (node_modules, caches) — use --all to remove them too.\n", skipped)
	}
	return nil
}

// removeTemplGenerated deletes *_templ.go, which templ regenerates from the
// .templ files next to them.
func removeTemplGenerated() (int, error) {
	var n int
	err := filepath.WalkDir(".", func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return nil // unreadable dirs are not our problem here
		}
		if d.IsDir() {
			base := filepath.Base(path)
			if base == "node_modules" || base == ".git" || base == "build" {
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, "_templ.go") {
			if err := os.Remove(path); err != nil {
				return err
			}
			fmt.Printf("  removed %-24s regenerated by irgo project assets\n", path)
			n++
		}
		return nil
	})
	return n, err
}

func init() {
	register(command{
		noun: "project", verb: "clean", order: 10,
		summary: "Remove generated output",
		args:    "[--all]",
		usage: [][2]string{
			{"", "Generated code and build output"},
			{"--all", "Also the scaffolded native shells"},
		},
		notes: `Removes _templ.go, static/css/output.css, build/, tmp/ and dist/. With --all,
ios/Example and android/Example go too; they are scaffolded again on the next
build, which takes a gomobile rebuild.

Nothing you wrote is touched.`,
	})
}
