// Updating an existing project when the framework moves on.
//
// `irgo project new .` rewrites everything the template owns, which is right for a repo
// that IS generated output and catastrophic for a real project: handlers,
// templates and main.go are where the app lives. So files are split by who owns
// them, the same way irgo.package.toml is already treated as yours.
//
// Framework-owned files are scaffolding the CLI maintains and expects to match
// the version in use — the native shells, the hot-reload config, the CI
// workflows, the gitignore. Replacing them is the point of an upgrade.
//
// Your files are seeded once and then belong to you. irgo never rewrites them;
// when the template's version has changed it says so, so you can adopt what
// matters by hand.
package main

import (
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
)

// frameworkOwned lists path prefixes the CLI maintains. Everything else in the
// template is treated as the developer's.
var frameworkOwned = []string{
	".air.toml",  // build/watch config, must match what `irgo project assets` does
	".gitignore", // tracks which generated paths exist
	"ios/",       // native shell, regenerated by builds anyway
	"android/",   // native shell, regenerated by builds anyway
	// CLAUDE.md and AGENTS.md are one-line pointers at README.md, so keeping
	// them current costs nothing. README.md itself is NOT here: it is the
	// single source of truth for people and assistants, which means it is also
	// where a project describes itself. Rewriting it on upgrade would delete
	// that. It is seeded once and then yours, like irgo.package.toml —
	// `upgrade --diff` shows when the template's reference sections moved on.
	"CLAUDE.md",
	"AGENTS.md",

	// mobile/ is the gomobile bridge, not app code. It exists only because
	// gobind cannot bind two packages named "mobile", and its job is to
	// re-export the exact surface the native shells call. When that surface
	// changes, a project that keeps the old copy fails to compile against the
	// new framework — which is the very drift writeArtifactStamp exists to
	// catch. Custom native work belongs in IrgoPlugins.swift/kt or in a
	// native.Register call from app code, neither of which lives here.
	"mobile/",
}

// isFrameworkOwned reports whether irgo maintains this path.
func isFrameworkOwned(rel string) bool {
	for _, p := range frameworkOwned {
		if rel == p || strings.HasPrefix(rel, p) {
			return true
		}
	}
	return false
}

// runUpgrade refreshes framework-owned scaffolding and reports which of your
// files the template has since changed.
func runUpgrade(force, showDiff bool) error {
	if _, err := os.Stat("go.mod"); err != nil {
		return fmt.Errorf("no go.mod here — run irgo project upgrade from your project root")
	}
	modulePath, err := getModulePath()
	if err != nil {
		return fmt.Errorf("could not determine module path: %w", err)
	}

	var updated, unchanged int
	var drifted, failed []string

	err = fs.WalkDir(templateFS, "templates", func(path string, d fs.DirEntry, werr error) error {
		if werr != nil || d.IsDir() {
			return werr
		}
		rel := strings.TrimPrefix(path, "templates/")
		if rel == "github" || strings.HasPrefix(rel, "github/") {
			return nil // CI is handled by irgo project ci
		}
		rel = strings.TrimSuffix(rel, ".tmpl")

		want, rerr := templateFS.ReadFile(path)
		if rerr != nil {
			return rerr
		}
		body := renderTemplateBody(string(want), modulePath)

		have, herr := os.ReadFile(rel)
		if herr == nil && string(have) == body {
			unchanged++
			return nil
		}

		// Config is yours even though the template seeds it.
		if rel == packageConfigFile && herr == nil {
			return nil
		}

		if !isFrameworkOwned(rel) && herr == nil && !force {
			// Seeded once, yours since. Report rather than overwrite.
			drifted = append(drifted, rel)
			return nil
		}

		if dir := filepath.Dir(rel); dir != "." {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				failed = append(failed, fmt.Sprintf("%s: %v", rel, err))
				return nil
			}
		}

		// Overwriting a file that already exists and differs discards whatever
		// was there. Usually that is just the older template, but it may be a
		// deliberate local change — and the two are indistinguishable from
		// here, so keep a copy rather than guess.
		note := ""
		if herr == nil {
			bak := rel + ".irgo-bak"
			if werr := os.WriteFile(bak, have, 0o644); werr == nil {
				note = fmt.Sprintf("  (previous saved as %s)", bak)
			}
		}

		if err := os.WriteFile(rel, []byte(body), 0o644); err != nil {
			failed = append(failed, fmt.Sprintf("%s: %v", rel, err))
			return nil
		}
		fmt.Printf("  updated: %s%s\n", rel, note)
		updated++
		return nil
	})
	if err != nil {
		return err
	}

	// CI is framework-owned too, and irgo project ci already knows how to write it.
	if err := writeCIWorkflows(".", modulePath, true, false); err != nil {
		failed = append(failed, fmt.Sprintf(".github/workflows: %v", err))
	}

	fmt.Printf("\n%d file(s) updated, %d already current.\n", updated, unchanged)

	migrateDatastar()
	reportGoDirective()

	if len(failed) > 0 {
		fmt.Println()
		fmt.Println("Could not write:")
		for _, f := range failed {
			fmt.Printf("  %s\n", f)
		}
		fmt.Println()
		fmt.Println("Common causes: a read-only file, a directory where a file is")
		fmt.Println("expected (or the reverse), or no write permission here.")
		// Exit non-zero: a partially-applied upgrade must not look successful,
		// or the next build fails against a half-updated scaffold.
		return fmt.Errorf("%d file(s) could not be written", len(failed))
	}

	if len(drifted) > 0 {
		fmt.Println()
		fmt.Println("These differ from the current template, and are YOURS — not touched:")
		for _, f := range drifted {
			fmt.Printf("  %s\n", f)
		}
		fmt.Println()
		fmt.Println("That is expected for anything you have edited. Review them only if")
		fmt.Println("an upgrade note says the framework changed how they work.")
		if showDiff {
			fmt.Println()
			for _, f := range drifted {
				printTemplateDiff(f, modulePath)
			}
		} else {
			fmt.Println("  See what the template has now:  irgo project upgrade --diff")
			fmt.Println("  Overwrite them anyway:          irgo project upgrade --force")
		}
	}
	return nil
}

// renderTemplateBody substitutes the placeholders a scaffolded file uses.
func renderTemplateBody(body, modulePath string) string {
	return renderTemplate(body, filepath.Base(modulePath), modulePath, replaceDirective())
}

// renderTemplate resolves every placeholder a template can contain.
//
// There were three copies of this list — new, its example scaffolder, and
// upgrade — so a placeholder added to one silently stayed literal in the
// others. {{COMMANDS}} did exactly that: the generated README shipped with the
// text "{{COMMANDS}}" where the command reference should have been.
func renderTemplate(body, projectName, modulePath, replace string) string {
	body = strings.ReplaceAll(body, "{{PROJECT_NAME}}", projectName)
	body = strings.ReplaceAll(body, "{{PROJECT_IDENT}}", sanitizeIdentifier(projectName))
	body = strings.ReplaceAll(body, "{{BUNDLE_IDENT}}", sanitizeBundleIdent(projectName))
	body = strings.ReplaceAll(body, "{{MODULE_PATH}}", modulePath)
	body = strings.ReplaceAll(body, "{{GO_VERSION}}", scaffoldGoVersion())
	body = strings.ReplaceAll(body, "{{REPLACE_DIRECTIVE}}", replace)
	body = strings.ReplaceAll(body, "{{COMMANDS}}", renderCommandTable())
	return body
}

// printTemplateDiff shows what the template holds for a file you own, so an
// upstream change can be adopted deliberately.
func printTemplateDiff(rel, modulePath string) {
	for _, cand := range []string{"templates/" + rel, "templates/" + rel + ".tmpl"} {
		want, err := templateFS.ReadFile(cand)
		if err != nil {
			continue
		}
		tmp, terr := os.CreateTemp("", "irgo-template-*")
		if terr != nil {
			return
		}
		defer os.Remove(tmp.Name())
		_, _ = tmp.WriteString(renderTemplateBody(string(want), modulePath))
		tmp.Close()

		fmt.Printf("── %s ── (left: yours, right: template)\n", rel)
		// diff exits non-zero when files differ, which is the normal case here.
		_ = runCommand("diff", "-u", rel, tmp.Name())
		fmt.Println()
		return
	}
}

// reportGoDirective points out a go.mod requiring more than irgo does.
//
// `irgo project new` used to write the scaffolding machine's Go version, so
// projects created on a newer toolchain demand it from every teammate and
// every CI runner — the docs site failed that way, requiring 1.26.5 from a
// runner with 1.24. New projects get irgo's floor now, but go.mod is yours and
// never rewritten, so an existing project keeps whatever it was given. This
// says so rather than leaving it to be discovered on someone else's machine.
func reportGoDirective() {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return
	}
	have := ""
	for _, line := range strings.Split(string(data), "\n") {
		if v, ok := strings.CutPrefix(strings.TrimSpace(line), "go "); ok {
			have = strings.TrimSpace(v)
			break
		}
	}
	if have == "" || !higherThan(have, minGoVersion) {
		return
	}
	fmt.Println()
	fmt.Printf("go.mod requires Go %s, and irgo needs only %s.\n", have, minGoVersion)
	fmt.Println("That was this project's scaffolding machine, not a requirement — it")
	fmt.Println("makes every teammate and CI runner install that exact toolchain.")
	fmt.Printf("  Lower it:  go mod edit -go=%s && go mod tidy\n", minGoVersion)
	fmt.Println("Keep it if something here genuinely needs the newer Go.")
}

// higherThan compares two Go versions field by field.
func higherThan(a, b string) bool {
	as, bs := strings.Split(a, "."), strings.Split(b, ".")
	for i := 0; i < len(as) && i < len(bs); i++ {
		x, y := atoiSafe(as[i]), atoiSafe(bs[i])
		if x != y {
			return x > y
		}
	}
	return len(as) > len(bs)
}

// migrateDatastar moves a project off its vendored Datastar client.
//
// Projects created before the client moved into the framework downloaded one
// at scaffold time and kept it forever, so each is pinned to whatever was
// current that day — one of them a release candidate running against a stable
// library. The framework serves the matching client now, and the stale copy is
// dead weight that the layout still points at.
//
// layout.templ belongs to the project, so only the one script tag is rewritten
// and the change is announced. A build constraint and a script source are the
// two edits irgo makes to files it does not own; both are mechanical, and both
// beat the failure they replace.
func migrateDatastar() {
	const vendored = "static/js/datastar.js"
	const oldTag = `<script type="module" src="/static/js/datastar.js"></script>`
	const newTag = `<script type="module" src="/_irgo/datastar.js"></script>`

	layout := filepath.Join("templates", "layout.templ")
	data, err := os.ReadFile(layout)
	if err != nil {
		return
	}
	if !strings.Contains(string(data), oldTag) {
		return
	}
	// Every occurrence: the scaffolded layout defines more than one page
	// shell, each with its own script tags, and replacing the first left the
	// fullscreen layout still loading a client that had just been deleted.
	updated := strings.ReplaceAll(string(data), oldTag, newTag)
	if err := os.WriteFile(layout, []byte(updated), 0o644); err != nil {
		return
	}
	fmt.Println()
	fmt.Printf("  updated: %s — Datastar now comes from the framework\n", layout)
	if pathExists(vendored) {
		if err := os.Remove(vendored); err == nil {
			fmt.Printf("  removed: %s (was pinned to whatever was current when this\n", vendored)
			fmt.Println("           project was created; irgo serves the matching client now)")
		}
	}
}
